In [1]:
import numpy as np

from nsga_population import Population, ClassicalPopulation
from individual import Individual, PermutationChromosome

In [2]:
n_machines = 3
n_jobs = 3
jssp_problem = np.array([
          # Technological sequence. Each row represents one job J. Each column represents the operation index.
          [[2, 3, 1],
           [1, 2, 3],
           [1, 3, 2]],
          # The second matrix contains the processing time
          [[1, 5, 2],
           [3, 3, 5],
           [2, 2, 4]]

])

test = ClassicalPopulation(N=50, decoding_method="apply_operation_based_bierwirth", n_jobs=n_jobs, n_machines=n_machines, objectives=["Makespan", "Mean Completion Time"], 
                           activate_schedule=True, tournament_size=2, mating_pool_size=50, mutation_probability=0.3, jssp_problem=jssp_problem)


In [24]:
np.random.seed(0)
donator = np.repeat(np.arange(n_jobs), n_machines)[np.argsort(np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines))]
print(donator)
np.random.seed(0)
receiver = np.repeat(np.arange(n_jobs), n_machines)[np.argsort(np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines))]
print(receiver)
result_indiv = test.gox_crossover(donator, receiver)
print(receiver)
print(donator)

[0 2 0 1 1 2 0 2 1]
[0 2 0 1 1 2 0 2 1]
Good lenght from GOX
[0 2 0 1 1 2 0 2 1]
[0 2 0 1 1 2 0 2 1]


In [25]:
result_indiv.permutation

array([0, 2, 0, 1, 1, 2, 0, 2, 1])

In [20]:
np.random.seed(1)
np.repeat(np.arange(n_jobs), n_machines)[np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines)]

array([1, 2, 1, 0, 0, 0, 2, 2, 0])

In [10]:
#np.random.seed(0)
np.repeat(np.arange(n_jobs), n_machines)[np.argsort(np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines))]

array([1, 2, 0, 1, 2, 1, 0, 2, 0])

In [1]:
class Test:
    def __init__(self):
        print("start")
        self.start = "test"

    def __setattr__(self, name, value):
        print(name, value)

In [2]:
Test()

start
start test


In [4]:
PermutationChromosome.create_permutation_chromosome(10, 10, ["Makespan", "Mean Flow Time"], watch_individual=True)

Attempting to set time_log to False
Attempting to set timer_result to {}
Attempting to set permutation to []
Attempting to set n_machines to 10
Attempting to set n_jobs to 10
Attempting to set objectives to ['Makespan', 'Mean Flow Time']
Attempting to set permutation to [9 9 7 7 3 0 5 7 1 9 1 5 6 7 3 5 3 3 2 0 2 2 5 0 0 5 8 7 6 7 9 8 2 8 1 9 9
 9 5 4 6 6 0 8 8 1 8 1 4 7 0 1 6 3 7 6 7 2 2 0 4 4 3 6 2 0 0 8 4 9 5 3 6 8
 4 9 1 5 6 1 8 1 4 1 2 6 2 4 4 5 9 4 8 3 0 3 5 7 2 3]
