In [4]:
import numpy as np

from nsga_population import Population, ClassicalPopulation
from individual import Individual, PermutationChromosome
from direct_representations import apply_operation_based_bierwirth
from or_benchmark import BenchmarkCollection
from schedules import Schedule
from operations import Operation

In [5]:
n_machines = 3
n_jobs = 3
jssp_problem = np.array([
          # Technological sequence. Each row represents one job J. Each column represents the operation index.
          [[2, 3, 1],
           [1, 2, 3],
           [1, 3, 2]],
          # The second matrix contains the processing time
          [[1, 5, 2],
           [3, 3, 5],
           [2, 2, 4]]

])

test = ClassicalPopulation(N=50, decoding_method="apply_operation_based_bierwirth", n_jobs=n_jobs, n_machines=n_machines, objectives=["Makespan", "Mean Completion Time"], 
                           activate_schedule=True, tournament_size=2, mating_pool_size=50, mutation_probability=0.3, jssp_problem=jssp_problem)


In [6]:
np.random.seed(0)
donator = np.repeat(np.arange(n_jobs), n_machines)[np.argsort(np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines))]
print(donator)
np.random.seed(0)
receiver = np.repeat(np.arange(n_jobs), n_machines)[np.argsort(np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines))]
print(receiver)
result_indiv = test.gox_crossover(donator, receiver)
print(receiver)
print(donator)

[0 2 0 1 1 2 0 2 1]
[0 2 0 1 1 2 0 2 1]
[0 2 0 1 1 2 0 2 1]
[0 2 0 1 1 2 0 2 1]


In [7]:
result_indiv.permutation

array([0, 2, 0, 1, 1, 2, 0, 2, 1])

In [8]:
np.random.seed(1)
np.repeat(np.arange(n_jobs), n_machines)[np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines)]

array([1, 2, 1, 0, 0, 0, 2, 2, 0])

In [9]:
#np.random.seed(0)
np.repeat(np.arange(n_jobs), n_machines)[np.argsort(np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines))]

array([2, 0, 1, 0, 1, 1, 0, 2, 2])

In [10]:
class Test:
    def __init__(self):
        print("start")
        self.start = "test"

    def __setattr__(self, name, value):
        print(name, value)

In [11]:
Test()

start
start test


In [12]:
PermutationChromosome.create_permutation_chromosome(10, 10, ["Makespan", "Mean Flow Time"], watch_individual=True)

Attempting to set time_log to False
Attempting to set timer_result to {}
Attempting to set permutation to []
Attempting to set n_machines to 10
Attempting to set n_jobs to 10
Attempting to set objectives to ['Makespan', 'Mean Flow Time']
Attempting to set permutation to [0 4 8 9 6 7 5 1 4 1 5 3 5 1 8 1 5 0 9 9 5 5 7 4 1 2 1 0 3 7 2 0 3 8 5 8 8
 4 8 7 8 2 6 6 4 6 5 1 3 3 8 3 1 3 2 3 2 3 7 9 9 4 6 7 9 2 6 1 4 5 2 4 2 6
 7 9 4 2 7 0 7 3 7 4 9 0 8 6 0 0 5 2 6 6 0 0 1 8 9 9]


In [13]:
problems = BenchmarkCollection(False)

In [78]:
problems.benchmark_collection["ft06"]

{'name': 'ft06',
 'description': 'Fisher and Thompson 6x6 instance, alternate name (mt06)',
 'problem_matrix': array([[[ 2,  0,  1,  3,  5,  4],
         [ 1,  2,  4,  5,  0,  3],
         [ 2,  3,  5,  0,  1,  4],
         [ 1,  0,  2,  3,  4,  5],
         [ 2,  1,  4,  5,  0,  3],
         [ 1,  3,  5,  0,  4,  2]],
 
        [[ 1,  3,  6,  7,  3,  6],
         [ 8,  5, 10, 10, 10,  4],
         [ 5,  4,  8,  9,  1,  7],
         [ 5,  5,  5,  3,  8,  9],
         [ 9,  3,  5,  4,  3,  1],
         [ 3,  3,  9, 10,  4,  1]]]),
 'n_jobs': 6,
 'n_machines': 6}

In [79]:
n_jobs = problems.benchmark_collection["ft06"]["n_jobs"]
n_machines = problems.benchmark_collection["ft06"]["n_machines"]
jssp_problem = problems.benchmark_collection["ft06"]["problem_matrix"]

In [87]:
#cur_permutation = np.array([14, 16, 13,  8,  1, 17, 16, 16,  5, 10, 11, 19, 19, 17,  1, 14, 10,
#        6, 14, 10, 14,  4, 19,  6, 11, 13,  4,  4, 13,  1,  0, 17,  0, 11,
#        5,  5, 18,  3, 15,  5,  3, 18,  9,  6, 18, 16, 11,  2,  6, 13, 15,
#       10,  9,  2,  5, 15, 10, 12, 15,  9, 18,  3,  1,  9,  7,  3,  8,  7,
#        4, 17,  7,  8,  0,  6,  3, 11, 17,  0, 19,  0,  2,  2, 16, 12, 12,
#        7,  2, 12, 14,  8,  8,  1,  9, 19, 18, 13,  7, 15, 12,  4])
cur_permutation = np.array([0,1,0,2,2,1,3,2,3,5,4,1,0,5,2,5,4,3,4,2,3,1,5,0,3,1,5,0,4,5,2,3,4,1,0,4]) #np.repeat(np.arange(n_jobs), n_machines)[np.argsort(np.random.randint(n_jobs*n_machines, size=n_jobs*n_machines))]

In [88]:
import copy
def activate_schedule_old(permutation, n_machines, n_jobs, jssp_problem):
        # Performs the Hybrid gifflar and thompson algorithm proposed by (Varela et al., 2005)
        # Input is the operation sequence, the technical sequence and the duration matrix
        active_schedule = []
        # Making a copy of the semi activve schedule
        semi_active_schedule = copy.deepcopy(permutation.tolist())
        # Initiating the timing lists for machine and job
        m_time = np.zeros(n_machines)
        j_time = np.zeros(n_jobs)
        T_counter = np.zeros(n_jobs, dtype=int) 
        

        while len(semi_active_schedule) > 0:
            # Need to find the operation with the lowest completion time among the set of scheduable operations
            cur_schedulable_index = np.ones(n_jobs, dtype=int) * -1
            cur_best_index_k = 0
            cur_lowest_complete_time = 0
            # Extract the start and comlpetion time for the first operation in the list
            #lowest_start_time_i  = np.max([m_time[semi_active_schedule[0].machine], j_time[semi_active_schedule[0].job]])
            cur_lowest_complete_time = np.inf#lowest_start_time_i + semi_active_schedule[0].duration
            i = 0
            while np.any(cur_schedulable_index == -1) and (i < len(semi_active_schedule)):

                cur_job = semi_active_schedule[i]
                if cur_schedulable_index[cur_job] == -1: #cur_next_machine == semi_active_schedule[i].machine:
                    # If the current operation matches the machine, it is regarded as schedulable
                    cur_schedulable_index[cur_job] = i
                    cur_machine = jssp_problem[0][cur_job][T_counter[cur_job]]
                    lowest_start_time_i  = np.max([m_time[cur_machine], j_time[cur_job]])
                    completion_i = lowest_start_time_i + jssp_problem[1][cur_job][T_counter[cur_job]]
                    
                    if completion_i < cur_lowest_complete_time:
                        # Update the lowest completion time if it is lower than the current lowest
                        cur_lowest_complete_time = completion_i
                        # store the index of the operation
                        cur_best_index_k = i

                i += 1

            # The lowest completion time
            found_lowest_completion_time = cur_lowest_complete_time
            # The machine number of the selected operation
            machine_k = jssp_problem[0][semi_active_schedule[cur_best_index_k]][T_counter[semi_active_schedule[cur_best_index_k]]]
            # The candidate set that contians the further reduced schedulable operations
            B = []
            for operation_index in cur_schedulable_index:
                # Find the operation with the lowest start time
                cur_job = semi_active_schedule[operation_index]
                cur_machine = jssp_problem[0][cur_job][T_counter[cur_job]]
                lowest_start_time_i  = np.max([m_time[cur_machine], j_time[cur_job]])
                if (cur_machine == machine_k) and (lowest_start_time_i < found_lowest_completion_time):
                    # If the current operation is for machine_k and the start time is lower than the lowest completion time
                    # Regard it as part of the candidate operations
                    B.append(operation_index)
                    # Check if the start time 
                    #if  & (overall_lowest_start_time > lowest_start_time_i):
                        # If the starting time is lower than the the lowest completion time and the start time is lower than the previous lowest start time
                        # Store index and start time for that operation
                    #    overall_best_index = operation_index
                    #    overall_lowest_start_time = lowest_start_time_i
                    
            # Scedule the selected operation

            # Find the leftmose operation in the chromosome that is part of candidate set B
            print(B)
            selected_operation = np.min(B)
            cur_job = semi_active_schedule[selected_operation]
            cur_machine = jssp_problem[0][cur_job][T_counter[cur_job]]
            cur_duration = jssp_problem[1][cur_job][T_counter[cur_job]]
            selected_operation_start = np.max([m_time[cur_machine], j_time[cur_job]])
            cur_operation = Operation(cur_job, cur_machine, cur_duration, selected_operation_start)
            # Update the job and machine next counters
            m_time[cur_machine] = cur_operation.get_completion_time()
            j_time[cur_job] = cur_operation.get_completion_time()
            # Add to the machine index counter
            T_counter[cur_operation.job] += 1
            # Remove the operation from the permutation
            semi_active_schedule.pop(selected_operation)
            active_schedule.append(cur_operation)
        
        return active_schedule

In [89]:
np.unique(cur_permutation, return_counts=True)

(array([0, 1, 2, 3, 4, 5]), array([6, 6, 6, 6, 6, 6], dtype=int64))

In [90]:
operation_list = activate_schedule_old(cur_permutation, n_machines, n_jobs, jssp_problem)

[0, 3, 10]
[0, 5, 8]
[0]
[0, 7]
[0]
[7, 1, 4]
[0, 4]
[5, 2]
[0]
[0]
[3]
[6, 0]
[1]
[0]
[2]
[0]
[1]
[4, 0]
[1]
[4, 1]
[10, 0]
[0, 7]
[1]
[7, 1]
[0]
[2, 6, 3]
[8, 4, 1]
[2]
[3, 1, -1]
[0, 1]
[5, 1, -1]
[0]
[-1, 3, 2, -1]
[-1, -1, 2, -1]
[-1, -1, 1, -1, -1]
[-1, -1, 0, -1, -1, -1]


In [19]:
operation_list = apply_operation_based_bierwirth(n_jobs, n_machines=n_machines, j_rep_permutation=cur_permutation ,jssp_problem=jssp_problem)

In [85]:
cur_schedule = Schedule(operation_list, n_jobs, n_machines, jssp_problem, "Makespan", "Mean Completion Time")

In [86]:
str(cur_schedule.get_operation_code_list()).replace("[", "").replace("]", "").replace("'", "").replace(" ", "")


'A1,B1,A2,C1,C2,D1,B2,F1,C3,D2,F2,E1,A3,B3,E2,C4,D3,F3,C5,D4,E3,B4,A4,D5,F4,A5,F5,F6,E4,B5,A6,E5,B6,E6,D6,C6'

In [22]:
cur_schedule.activate_schedule()

In [23]:
str(cur_schedule.get_operation_code_list()).replace("[", "").replace("]", "").replace("'", "").replace(" ", "")

'K1,O1,N1,Q1,I1,O2,Q2,K2,F1,B1,Q3,G1,R1,Q4,L1,O3,B2,T1,K3,T2,R2,G2,O4,K4,B3,L2,E1,E2,T3,N2,R3,L3,I2,F2,G3,N3,E3,L4,K5,G4,A1,F3,B4,A2,N4,S1,G5,H1,F4,L5,D1,S2,F5,Q5,E4,M1,S3,B5,P1,R4,S4,J1,I3,N5,D2,D3,R5,C1,J2,S5,P2,P3,D4,C2,H2,E5,J3,I4,D5,P4,A3,H3,J4,C3,I5,A4,A5,T4,M2,C4,H4,M3,P5,J5,C5,M4,T5,H5,O5,M5'