In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

3x3 - jssp
first the m zeros are placed in m places among j x m places.

0  - 0,1,2
1  - 0,1,3
2  - 0,1,4
3  - 0,1,5
4  - 0,1,6
5  - 0,1,7
6  - 0,1,8
7  - 0,2,3
8  - 0,2,4
9  - 0,2,5
10 - 0,2,6
11 - 0,2,7
12 - 0,2,8
13 - 0,3,4
14 - 0,3,5

In [2]:
math.factorial(9)

362880

In [3]:
def get_permutation(n: int, j: int):
        """This method is used to map an integer n to a permutation of j job numbers (j! possible permutations).
        Thus n must be between 0 and j!-1

        Parameters
        ----------
        n : int
            Permuation number
        j : int
            number of jobs (permutation size)
        """
        i = j
        p_next = n
        result = np.empty(i, dtype=int)
        selectables = np.arange(i)
        for k in range(len(result)):
            j = i - k - 1
            cur_select_index = int(p_next / math.factorial(j))
            cur_job_number = selectables[selectables != -1][cur_select_index]
            result[k] = cur_job_number
            # Remove cur_job number form available jobs for next iteration
            selectables[cur_job_number] = -1
            p_next = p_next % math.factorial(j)

        return result

24


In [18]:
j = 3
m = 3

new_list = []
for i in range(j):
    for k in range(m):
        new_list.append(i)

max_num_individuals = math.factorial(j*m)#math.factorial(j*m)/(math.factorial(m)**j)
step_length = math.factorial(m)**j
print(max_num_individuals)
ref_list = np.array(new_list)
temp_list = []
n_unique_accum = []
for i in range(int(max_num_individuals)):
    cur_index = i #* step_length
    cur_result = ref_list[get_permutation(cur_index, j*m)]
    print(cur_result)
    temp_list.append(str(cur_result))
    n_unique_accum.append(len(set(temp_list)))

print(len(set(temp_list)))
print(n_unique_accum)
plt.plot(np.arange(0, int(max_num_individuals)), n_unique_accum)

362880
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 1 2 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 1 2 2]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 1 2 2 1 2]
[0 0 0 1 1 2 2 2 1]
[0 0 0 1 2 1 1 2 2]
[0 0 0 1 2 1 

KeyboardInterrupt: 

In [8]:
np.array([0,0,0,1,1,1,2,2,2])[[0, 5, 3, 2, 1, 6, 8, 4, 7]]

array([0, 1, 1, 0, 0, 2, 2, 1, 2])

In [9]:
temp_list

['[0 0 0 1]',
 '[0 0 1 0]',
 '[0 0 0 1]',
 '[0 0 1 0]',
 '[0 1 0 0]',
 '[0 1 0 0]',
 '[0 0 0 1]',
 '[0 0 1 0]',
 '[0 0 0 1]',
 '[0 0 1 0]',
 '[0 1 0 0]',
 '[0 1 0 0]',
 '[0 0 0 1]',
 '[0 0 1 0]',
 '[0 0 0 1]',
 '[0 0 1 0]',
 '[0 1 0 0]',
 '[0 1 0 0]',
 '[1 0 0 0]',
 '[1 0 0 0]',
 '[1 0 0 0]',
 '[1 0 0 0]',
 '[1 0 0 0]',
 '[1 0 0 0]']